version: "3"

services:
  xyz_spaceframe_io:
    image: nginx:stable-alpine
    build: .
    container_name: xyz_spaceframe_io
    ports:
      - 8020
    volumes:
      # - ./src:/usr/share/nginx/html
      - ./dist/xyz.spaceframe.io:/usr/share/nginx/html

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xyz_spaceframe_io.entrypoints=websecure"
      - "traefik.http.routers.xyz_spaceframe_io.rule=Host(`xyz.spaceframe.io`)"
      - "traefik.http.routers.xyz_spaceframe_io.tls.certresolver=myresolver"
      - "traefik.port=8015"

      # Enable gzip compression
      - "traefik.http.routers.xyz_spaceframe_io.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"

    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
